### ISSUE TITLE
✨ feature: support gitmoji

### ISSUE THREAD

**Issue by Sanjeever** [lynxife/auto-commit#1]
For example following [gitmoji.dev](https://gitmoji.dev/)
---
template :  
```
<intention> [scope?][:?] <message>
```
- intention: An emoji from the list.
- scope: An optional string that adds contextual information for the scope of the change.
- message: A brief explanation of the change.

> Using emojis on commit messages provides an easy way of identifying the purpose or intention of a commit with only looking at the emojis used. As there are a lot of different emojis I found the need of creating a guide that can help to use emojis easier.

**Comment by lynxife** [comment]
Okay, I will consider providing it as a configuration, Thank you for your suggestion.

**Comment by lynxife** [comment]
v0.0.4 release, close this issue.
